### ISSUE TITLE
Document all important services

### ISSUE THREAD

**Issue by PotentialStyx** [PotentialStyx/govaldocs#4]
# Done

# WIP
- [ ] Chat - Now only used for <code>.draw</code> file multiplayer, but used to power repl chat.
     * Just need to add docs for message history
- [ ] Chan0 - Manages channels, and pongs pings.
- [ ] OT - Powers file editing.

# TODO
- [ ] Shellrun2 - Powers the console tab.
- [ ] Shell - Powers the shell tab.
- [ ] Exec - Let's the client run commands. Powers the git pane, as well as the resource pane.
- [ ] GCSFile - Powers the filetree.
- [ ] FSEvents - Let's the client know of file modification events.
- [ ] dotreplit - Lets the editor read and edit the state of the <code>.replit</code> file.
- [ ] toolchain - Lets the client know what LSP's, package managers, debuggers, and run commands are available.
- [ ] LSP - Powers code intelligence.
- [ ] Presence - Let's the client know who else is in the repl, and what file they are in.
- [ ] Audio - Powers non-VNC audio in repls.
- [ ] Snapshot - Let's the client tell the server when to snapshot and persist all file changes.
- [ ] Packager3 - Powers the packager tab.
