### ISSUE TITLE
Document other services

### ISSUE THREAD

**Issue by PotentialStyx** [PotentialStyx/govaldocs#6]
# Done

# WIP

# TODO
- [ ] Socket - Opens a TCP/UDP socket in the container.
- [ ] Shellrun - Predecessor to shellrun2.
- [ ] Interp2 - Direct interface to prybar.
- [ ] Run2 - Runs the compile command if present, then the entrypoint.
- [ ] File/Files - Provides access to the containers fs, changes don't persist across container reboots unlike gcsfiles. 

# Need more info
- [ ] Fileauth - Related to gcsfiles

# Deprecated services
- [ ] Format - Replaced with LSP
- [ ] Lint - Replaced with LSP
- [ ] Eval - Replaced with Interp
- [ ] Interp - Replaced with Interp2
- [ ] Packager - Replaced by Packager2
- [ ] Packager2 - Replaced with Packager3
- [ ] Run - Replaced with Run2
- [ ] Unittest - Was only used in classroom
